name: Universal_Shop_Plugin
main: io.github.sharkstudios.USP.Main
version: 1.0.4
loadbefore: [Vault]
depend: [Vault]
commands:
   sklep:
      description: Otwiera sklep
      usage: /<command>
      permission: usp.shop
      permission-message: You don't have permission